#!/usr/bin/env sh

spacebar -m config position                    top
spacebar -m config display                     all
spacebar -m config height                      26
spacebar -m config title                       on
spacebar -m config spaces                      on
spacebar -m config clock                       on
spacebar -m config power                       on
spacebar -m config padding_left                20
spacebar -m config padding_right               20
spacebar -m config spacing_left                25
spacebar -m config spacing_right               15
spacebar -m config text_font                   "Helvetica Neue:Bold:12.0"
spacebar -m config icon_font                   "Font Awesome 6 Free:Solid:16.0"
spacebar -m config background_color            0xff101010
spacebar -m config foreground_color            0x88a8a8a8
spacebar -m config power_icon_color            0x88cd950c
spacebar -m config battery_icon_color          0x88d75f5f
spacebar -m config dnd_icon_color              0x88a8a8a8
spacebar -m config clock_icon_color            0x88a8a8a8
spacebar -m config power_icon_strip             
spacebar -m config space_icon                  
spacebar -m config space_icon_color            0xff17ec64
spacebar -m config space_icon_color_secondary  0xff78c4d4
spacebar -m config space_icon_color_tertiary   0xfffff9b0
#spacebar -m config space_icon_strip            1 2 3 4 5 6 7 8 9 10
spacebar -m config space_icon_strip            一 二 三  四 五 六 七 八 九 十
spacebar -m config spaces_for_all_displays     on
spacebar -m config clock_icon                  
spacebar -m config dnd_icon                    
spacebar -m config clock_format                "%d/%m/%Y %R"
spacebar -m config right_shell_icon            
spacebar -m config right_shell_icon_color      0x88a8a8a8
spacebar -m config right_shell_command         "~/.config/spacebar/vpn_status.sh"
spacebar -m config right_shell                 on
#spacebar -m config debug_output                on

echo "$(date +%Y%m%d%H%M) spacebar configuration loaded.."
