#!/usr/bin/env bash
#
# MacOS tweaks for Yabai
# https://github.com/koekeishiya/yabai/wiki#quickstart-guide

set -eEuo pipefail

# make Homebrew/personal installed apps visible to GUI apps (like Spotlight)
# https://docs.brew.sh/FAQ#my-mac-apps-dont-find-usrlocalbin-utilities
launchctlUserPath="$(plutil -convert json -o - -r /private/var/db/com.apple.xpc.launchd/config/user.plist \
  | jq -r '.PathEnvironmentVariable')"
# TODO check if paths are already in launchctlUserPath
sudo launchctl config user path "/usr/local/bin:$launchctlUserPath"
if [[ -d "$HOME/bin" ]] ; then
  sudo launchctl config user path "$HOME/bin:$launchctlUserPath"
fi

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Enable the 'reduce transparency' option on Yosemite. Save GPU cycles.
defaults write com.apple.universalaccess reduceTransparency -bool true

# Enable the 'reduce motion' option. Faster Space switching
defaults write com.apple.universalaccess reduceMotion -bool true

## Fix folder opened from desktop not tiling in 
defaults write com.apple.finder DisableAllAnimations -bool true
# to reset system defaults, delete the key instead
# defaults delete com.apple.finder DisableAllAnimations

## Dock

# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 0

# Extend the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 3

# Remove the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -float 0

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Minimize windows into their application’s icon
defaults write com.apple.dock minimize-to-application -bool true

## Spaces

# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Displays have separate Spaces
defaults write com.apple.spaces spans-displays -bool true

# Wipe all (default) app icons from the Dock
# This is only really useful when setting up a new Mac, or if you don’t use
# the Dock to launch apps.
#defaults write com.apple.dock persistent-apps -array

# Shortcuts
#
# see: https://support.apple.com/en-us/HT201236
#
# The meta-keys are set as
#   @ for Command
#   $ for Shift
#   ~ for Alt
#   ^ for Ctrl.
# 'k' in this example is the non-meta-key that you want to use.
# '\\U2026' is the code for an elipsis, useful in menu items
#
# For Application-specific commands, use the following:
#  defaults write com.developer.app NSUserKeyEquivalents -dict-add "Menu Item" -string "@$~^k"
# For system-wide shortcuts, you can use -g instead of the app identifier, e.g.
#  defaults write -g NSUserKeyEquivalents -dict-add "Menu Item" -string "@$~^k"
#
# Note that you'll need to relaunch the app before these will take effect. Also
# you can see if they've been successful in System Preferences -- which will also
# need a relaunch to show the changes.

echo "Done. Note that some of these changes require a logout/restart to take effect."
