#!/usr/bin/env sh
# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_zoom_persist          on
yabai -m config window_shadow                float         # SIP
yabai -m config window_opacity               off           # SIP
# disabled due to a bug in Apple Big Sur
#yabai -m config window_opacity_duration      0.0           # SIP
yabai -m config active_window_opacity        1.0           # SIP
yabai -m config normal_window_opacity        0.90          # SIP
yabai -m config window_animation_duration    0.0           # SIP
yabai -m config window_animation_frame_rate  30            # SIP
yabai -m config insert_feedback_color        0xff35357a
yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
